# Introduction à la programmation

## Analyzing Patient Data

In [1]:
import numpy

In [2]:
numpy.loadtxt(fname='inflammation-01.csv', delimiter=",")

array([[ 0.,  0.,  1., ...,  3.,  0.,  0.],
       [ 0.,  1.,  2., ...,  1.,  0.,  1.],
       [ 0.,  1.,  1., ...,  2.,  1.,  1.],
       ..., 
       [ 0.,  1.,  1., ...,  1.,  1.,  1.],
       [ 0.,  0.,  0., ...,  0.,  2.,  0.],
       [ 0.,  0.,  1., ...,  1.,  1.,  0.]])

In [3]:
weight_kg = 55

In [4]:
print(weight_kg)

55


In [5]:
print("Weight in pounds:", 2.2*weight_kg)

Weight in pounds: 121.00000000000001


In [6]:
print(1)

1


In [7]:
print(1.)

1.0


In [8]:
weight_kg = 57.5

In [9]:
print(weight_kg)

57.5


In [10]:
weight_lbs = 2.2*weight_kg

In [11]:
print("in kg:", weight_kg, " in pounds:", weight_lbs)

in kg: 57.5  in pounds: 126.50000000000001


In [12]:
weight_kg = 100

In [13]:
print("in kg:", weight_kg, " in pounds:", weight_lbs)

in kg: 100  in pounds: 126.50000000000001


In [14]:
data = numpy.loadtxt(fname="inflammation-01.csv", delimiter=",")

In [15]:
print(data)

[[ 0.  0.  1. ...,  3.  0.  0.]
 [ 0.  1.  2. ...,  1.  0.  1.]
 [ 0.  1.  1. ...,  2.  1.  1.]
 ..., 
 [ 0.  1.  1. ...,  1.  1.  1.]
 [ 0.  0.  0. ...,  0.  2.  0.]
 [ 0.  0.  1. ...,  1.  1.  0.]]


In [16]:
print(type(data))

<class 'numpy.ndarray'>


In [17]:
print(data.shape)

(60, 40)


In [19]:
print("first value is:", data[0,0])

first value is: 0.0


In [20]:
print("middle value is:", data[30,20])

middle value is: 13.0


In [21]:
print(data[5:10, 10:20])

[[  7.   6.   6.   9.   9.  15.   4.  16.  18.  12.]
 [  6.   5.  11.   9.   4.  13.   5.  12.  10.   6.]
 [  7.   8.   8.   5.  10.   9.  15.  11.  18.  19.]
 [  2.   4.  11.  12.  10.  11.   9.  10.  17.  11.]
 [  6.   8.  12.   5.  13.   6.  13.   8.  16.   8.]]


In [22]:
print(data[:3, 30:])

[[  4.   4.   5.   7.   3.   4.   2.   3.   0.   0.]
 [  3.   5.   4.   4.   5.   5.   1.   1.   0.   1.]
 [ 10.   5.   4.   2.   2.   3.   2.   2.   1.   1.]]


In [23]:
print(data[:3, :])

[[  0.   0.   1.   3.   1.   2.   4.   7.   8.   3.   3.   3.  10.   5.
    7.   4.   7.   7.  12.  18.   6.  13.  11.  11.   7.   7.   4.   6.
    8.   8.   4.   4.   5.   7.   3.   4.   2.   3.   0.   0.]
 [  0.   1.   2.   1.   2.   1.   3.   2.   2.   6.  10.  11.   5.   9.
    4.   4.   7.  16.   8.   6.  18.   4.  12.   5.  12.   7.  11.   5.
   11.   3.   3.   5.   4.   4.   5.   5.   1.   1.   0.   1.]
 [  0.   1.   1.   3.   3.   2.   6.   2.   5.   9.   5.   7.   4.   5.
    4.  15.   5.  11.   9.  10.  19.  14.  12.  17.   7.  12.  11.   7.
    4.   2.  10.   5.   4.   2.   2.   3.   2.   2.   1.   1.]]


In [24]:
small = data[:3, 30:]

In [25]:
print(data[:3, 30:])

[[  4.   4.   5.   7.   3.   4.   2.   3.   0.   0.]
 [  3.   5.   4.   4.   5.   5.   1.   1.   0.   1.]
 [ 10.   5.   4.   2.   2.   3.   2.   2.   1.   1.]]


In [26]:
print(small)

[[  4.   4.   5.   7.   3.   4.   2.   3.   0.   0.]
 [  3.   5.   4.   4.   5.   5.   1.   1.   0.   1.]
 [ 10.   5.   4.   2.   2.   3.   2.   2.   1.   1.]]


In [27]:
small[0,0] = 100.
print(small)

[[ 100.    4.    5.    7.    3.    4.    2.    3.    0.    0.]
 [   3.    5.    4.    4.    5.    5.    1.    1.    0.    1.]
 [  10.    5.    4.    2.    2.    3.    2.    2.    1.    1.]]


In [28]:
print(data[:3, 30:])

[[ 100.    4.    5.    7.    3.    4.    2.    3.    0.    0.]
 [   3.    5.    4.    4.    5.    5.    1.    1.    0.    1.]
 [  10.    5.    4.    2.    2.    3.    2.    2.    1.    1.]]


In [29]:
print(data)

[[ 0.  0.  1. ...,  3.  0.  0.]
 [ 0.  1.  2. ...,  1.  0.  1.]
 [ 0.  1.  1. ...,  2.  1.  1.]
 ..., 
 [ 0.  1.  1. ...,  1.  1.  1.]
 [ 0.  0.  0. ...,  0.  2.  0.]
 [ 0.  0.  1. ...,  1.  1.  0.]]


In [30]:
doubledata = data * 2.0

In [31]:
print(doubledata)

[[ 0.  0.  2. ...,  6.  0.  0.]
 [ 0.  2.  4. ...,  2.  0.  2.]
 [ 0.  2.  2. ...,  4.  2.  2.]
 ..., 
 [ 0.  2.  2. ...,  2.  2.  2.]
 [ 0.  0.  0. ...,  0.  4.  0.]
 [ 0.  0.  2. ...,  2.  2.  0.]]
